# Generated by Django 2.1 on 2019-01-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_id',
        ),
    ]
